console.log("try Catch")

try {
    console.log("Inside try block");
functionabc();
console.log("Inside the  block");
} catch (error) {
    console.log(error)
}